### ISSUE TITLE
Aplicar revisión a documento de Linea base

### ISSUE THREAD

**Issue by aandres-frc2021** [nahueldiazz/ISW_4K4_Grupo_7_2021#15]
Proyecto: Cursado
Solicitante: @aandres-frc2021 
Fecha: 19/04/2021
Cambio Solicitado: Se solicita revisar el documento de linea base y aplicar las correcciones necesarias.
Link: https://github.com/nahueldiazz/ISW_4K4_Grupo_7_2021/tree/master/Repositorio_Grupo07_2021/Linea_Base

**Comment by ghost** [comment]
Analizador del cambio: @lautarogoyenechea 
Componentes Afectados: G7_L_BASE_4_LineaBaseProductoCursado_1.docx
Comentario: N/A

**Comment by aandres-frc2021** [comment]
Fecha: 19/04/2021
Autor:  @aandres-frc2021 
Comentario: Se suben cambios en el archivo de linea base.

**Comment by ghost** [comment]
Fecha: 19/04/2021
Revisor: @lautarogoyenechea 
Comentario: Aprobado
